### PR TITLE
#2 Made the page little more attractive

### PR DESCRIPTION
**Pull request by mohitkumaragrawal**
Made the UI more attractive, changes include
 - improved hover effects on buttons
 - changed the default font 
 - tweaked the textarea styles
 - tweaked the dark theme to have a consistent color scheme
 - fixed the preview section to show multi-line text (before it was not rendering in multi-lines)
 - tweaked the styles of preview section
Any suggestions/changes are welcome.

### CODE REVIEW

**Comment by Dipti821** [comment]
@mohitkumaragrawal can u add the ss of the changes.

**Comment by mohitkumaragrawal** [comment]
# Dark Theme

image

** Preview Section
image

# Light Theme

image

** Preview Section
image

**Comment by mohitkumaragrawal** [comment]
@Dipti821 Check this out, If you want any amendments, please let me know.

**Comment by mohitkumaragrawal** [comment]
@Dipti821 Any thoughts?

image
image

**Review by Dipti821 — APPROVED** [review]
Looking good to me. Good Job @mohitkumaragrawal .

**Pull request merged**
