### PR TITLE
Bug in Capitalize first word [fixes #45]

### LINKED ISSUE #45: Bug in Capitalize first word
It is not capitalising the first word occuring in new line or just after some punctuation. Correct it.

### PR DESCRIPTION
**Pull request by najeebkp**
### Bug in Capitalize first word [fixes #45]

### CODE REVIEW

**Review by Dipti821 — CHANGES_REQUESTED** [review]
Don't change whole code by giving indentation , spaces or anything unnecessary. Just focus on the lines of code you are changing or adding.

**Comment by najeebkp** [comment]
@Dipti821 see, that is auto indentation. it will usually happen as different people follow different spacing. doesn't matter at all. no code changed. just added few lines. please check by running on your machine.

**Comment by Dipti821** [comment]
> @Dipti821 see, that is auto indentation. it will usually happen as different people follow different spacing. doesn't matter at all. no code changed. just added few lines. please check by running on your machine.

Its difficult for me to review. Add a ss/video clip of the changes.

**Review by Dipti821 — DISMISSED** [review]

**Comment by najeebkp** [comment]
Screenshot from 2022-10-09 16-29-54

Thats it !

**Pull request merged**
