### PR TITLE
Updated speak feature by adding pause feature and added their respective icons

### PR DESCRIPTION
**Pull request by ggautamgoyalg**
Initially it only consists of speak feature in which I have added pause feature so that user can pause the reading of text by computer. I also have added speak and pause icons to get user friendly interface

### CODE REVIEW

**Comment by Dipti821** [comment]
Add the ss /video clip of the changes.

**Comment by Dipti821** [comment]
And also link the PR with issue.

**Comment by ggautamgoyalg** [comment]
It's issue number #68

**Comment by ggautamgoyalg** [comment]
Screenshot (112)


Screenshot (114)

**Comment by ggautamgoyalg** [comment]
One is while text reading is paused and the other when it is not paused

**Review by Dipti821 — APPROVED** [review]
Good work!

**Comment by Dipti821** [comment]
@ggautamgoyalg there is some issue with speaking ,its not working see to it.

**Pull request merged**
