### PR TITLE
issue #63 added footer

### PR DESCRIPTION
**Pull request by amann013**

### CODE REVIEW

**Comment by Dipti821** [comment]
Add ss of the changes.

**Comment by amann013** [comment]
dark mode

Footer in light mode
light mode

Footer in dark mode

**Comment by Dipti821** [comment]
You have already added copyright icon so no use of copyright text ,remove it and give space between footer and the end of the website.

**Comment by amann013** [comment]
changed footer

please review it

**Review by Dipti821 — APPROVED** [review]

**Pull request merged**
