### PR TITLE
added the text to speech feature

### PR DESCRIPTION
**Pull request by sambhavgupta0705**
this pull request resolve issue #21

### CODE REVIEW

**Comment by Dipti821** [comment]
Resolve the conflict @sambhavgupta0705

**Comment by sambhavgupta0705** [comment]
https://user-images.githubusercontent.com/81870866/194682572-308ed0a3-1fe8-45f1-b1e5-af4602fec9f8.mp4

**Comment by Dipti821** [comment]
> TextUtils.-.Word.counter._.character.counter._.lowercase.to.uppercase._.uppercase.to.lowercase.Mozilla.Firefox.2022-10-08.07-34-37.mp4

Resolve the merge conflict.

**Comment by sambhavgupta0705** [comment]
resolved

> > TextUtils.-.Word.counter._.character.counter._.lowercase.to.uppercase._.uppercase.to.lowercase.Mozilla.Firefox.2022-10-08.07-34-37.mp4
> 
> Resolve the merge conflict.

**Pull request merged**
