### PR TITLE
resolved #3

### LINKED ISSUE #3: Add reverse text feature to it.

### PR DESCRIPTION
**Pull request by prabhat7k**

### CODE REVIEW

**Comment by prabhat7k** [comment]
@Dipti821 I've added this new PR for the reverse text feature.

**Comment by Dipti821** [comment]
Add a ss/video clip of the changes @prabhat7k .

**Comment by prabhat7k** [comment]
> Add a ss/video clip of the changes @prabhat7k .

image

image

**Comment by prabhat7k** [comment]
> 

I don't have the controls to link the PR to the issue.

**Comment by Dipti821** [comment]
> > 
> 
> I don't have the controls to link the PR to the issue.

You can just mention the issue no.

**Pull request merged**
