### PR TITLE
After changed the UI of website

### PR DESCRIPTION
**Pull request by BidyasagarAnupam**
I fixed issue #2. @Dipti821 Give me any suggestions for better UI.

### CODE REVIEW

**Comment by Dipti821** [comment]
@BidyasagarAnupam first pull upstream and resolve the conflict. Someone has changed the UI , once see it and make ur changes accordingly.

**Comment by BidyasagarAnupam** [comment]
Okay then I will

**Comment by BidyasagarAnupam** [comment]
When I pulled upstream then some errors are coming, that's why the code is not running
Screenshot (234)

Screenshot (233)

**Comment by Dipti821** [comment]
@BidyasagarAnupam for me no error is coming I have fetched upstream and run the code.

**Comment by BidyasagarAnupam** [comment]
Ok then I will check again

**Comment by BidyasagarAnupam** [comment]
Ok I soled that issue, now I am working on it

**Pull request closed without merging**
